build:
  maxIssues: 0

complexity:
  LargeClass:
    active: true
    threshold: 600
  LongMethod:
    active: true
    threshold: 80
  LongParameterList:
    active: true
    functionThreshold: 7
    constructorThreshold: 7

style:
  MaxLineLength:
    active: false

  MagicNumber:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

potential-bugs:
  ImplicitDefaultLocale:
    active: false
